var fakeData = [
  {
    courseID: "LCA54698MO",
    courseTitle: "Learn HTML bangla turorial A to Z",
    price: 120.99,
    courseThumbnail: "https://i.ytimg.com/vi/n_HhXXTJHFg/maxresdefault.jpg",
    createdBy: "Moshiur",
    createdByCategory: "Web Developer",
    enrolled: 125,
    lesson: 30,
    courseCategory: "Web Development",
    modiul: 61,
    videos: 420,
    duration: "120:50",
    quizzes: "No",
    level: "Basic",
    language: "Bangla",
    certificate: "Yes",
    courseAbout:
      " Lorem ipsum dolor sit amet consectetur adipisicing elit. Ab nobis obcaecati eius mollitia pariatur dignissimos animi sapiente neque provident exercitationem optio porro unde, repellendus consequuntur nisi magnam soluta nihil consectetur nam dicta explicabo cum natus esse nemo. Sed, sequi vel.",
    introVideoLink: "https://www.youtube.com/embed/n_HhXXTJHFg",
  },

  {
    courseID: "LCA54458MO",
    courseTitle: "CSS bangla turorial A to Z",
    price: 185.99,
    courseThumbnail: "https://i.ytimg.com/vi/lVT2V4zeYQQ/maxresdefault.jpg",
    createdBy: "Moshiur",
    createdByCategory: "Web Developer",
    enrolled: 105,
    lesson: 45,
    courseCategory: "Web Development",
    modiul: 61,
    videos: 420,
    duration: "120:50",
    quizzes: "No",
    level: "Basic",
    language: "Bangla",
    certificate: "Yes",
    courseAbout:
      " Lorem ipsum dolor sit amet consectetur adipisicing elit. Ab nobis obcaecati eius mollitia pariatur dignissimos animi sapiente neque provident exercitationem optio porro unde, repellendus consequuntur nisi magnam soluta nihil consectetur nam dicta explicabo cum natus esse nemo. Sed, sequi vel.",
    introVideoLink: "https://www.youtube.com/embed/lVT2V4zeYQQ",
  },

  {
    courseID: "LCA12398AN",
    courseTitle: "C programming Bangla Tutorial Course Plan",
    price: 146.99,
    courseThumbnail: "https://i.ytimg.com/vi/6Dl_gkr0Lmw/maxresdefault.jpg",
    createdBy: "Anisul Islam",
    createdByCategory: "Web Developer",
    enrolled: 525,
    lesson: 189,
    courseCategory: "Web Development",
    modiul: 61,
    videos: 420,
    duration: "120:50",
    quizzes: "No",
    level: "Basic",
    language: "Bangla",
    certificate: "Yes",
    courseAbout:
      " Lorem ipsum dolor sit amet consectetur adipisicing elit. Ab nobis obcaecati eius mollitia pariatur dignissimos animi sapiente neque provident exercitationem optio porro unde, repellendus consequuntur nisi magnam soluta nihil consectetur nam dicta explicabo cum natus esse nemo. Sed, sequi vel.",
    introVideoLink: "https://www.youtube.com/embed/6Dl_gkr0Lmw",
  },

  {
    courseID: "LCA51458AN",
    courseTitle: "Java Bangla Tutorials Introduction to Java",
    price: 166.99,
    courseThumbnail: "https://i.ytimg.com/vi/hf4k4OWlBfI/maxresdefault.jpg",
    createdBy: "Anisul Islam",
    createdByCategory: "Web Developer",
    enrolled: 195,
    lesson: 150,
    courseCategory: "Web Development",
    modiul: 61,
    videos: 420,
    duration: "120:50",
    quizzes: "No",
    level: "Basic",
    language: "Bangla",
    certificate: "Yes",
    courseAbout:
      " Lorem ipsum dolor sit amet consectetur adipisicing elit. Ab nobis obcaecati eius mollitia pariatur dignissimos animi sapiente neque provident exercitationem optio porro unde, repellendus consequuntur nisi magnam soluta nihil consectetur nam dicta explicabo cum natus esse nemo. Sed, sequi vel.",
    introVideoLink: "https://www.youtube.com/embed/hf4k4OWlBfI",
  },

  {
    courseID: "LCA24658JS",
    courseTitle: "Variables JavaScript Bangla Tutorial",
    price: 138.99,
    courseThumbnail: "https://i.ytimg.com/vi/w307avqohW8/maxresdefault.jpg",
    createdBy: "JS Bangladesh",
    createdByCategory: "Web Developer",
    enrolled: 425,
    lesson: 30,
    courseCategory: "Web Development",
    modiul: 61,
    videos: 420,
    duration: "120:50",
    quizzes: "No",
    level: "Basic",
    language: "Bangla",
    certificate: "Yes",
    courseAbout:
      " Lorem ipsum dolor sit amet consectetur adipisicing elit. Ab nobis obcaecati eius mollitia pariatur dignissimos animi sapiente neque provident exercitationem optio porro unde, repellendus consequuntur nisi magnam soluta nihil consectetur nam dicta explicabo cum natus esse nemo. Sed, sequi vel.",
    introVideoLink: "https://www.youtube.com/embed/w307avqohW8",
  },

  {
    courseID: "LCA45698JS",
    courseTitle: "01. Introduction to PHP | PHP The !DYING Language",
    price: 158.99,
    courseThumbnail: "https://i.ytimg.com/vi/Fre99th2ao4/maxresdefault.jpg",
    createdBy: "JS Bangladesh",
    createdByCategory: "Web Developer",
    enrolled: 263,
    lesson: 5,
    courseCategory: "Web Development",
    modiul: 61,
    videos: 420,
    duration: "120:50",
    quizzes: "No",
    level: "Basic",
    language: "Bangla",
    certificate: "Yes",
    courseAbout:
      " Lorem ipsum dolor sit amet consectetur adipisicing elit. Ab nobis obcaecati eius mollitia pariatur dignissimos animi sapiente neque provident exercitationem optio porro unde, repellendus consequuntur nisi magnam soluta nihil consectetur nam dicta explicabo cum natus esse nemo. Sed, sequi vel.",
    introVideoLink: "https://www.youtube.com/embed/Fre99th2ao4",
  },
];

export default fakeData;
